//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATO.net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        
        public Employee( String first,
                          String last,
                          Double annual,
                          int superrate,
                          int month,
                          Payslip paysl)
	  
	  {
	      firstName = first;
	      lastName = last;
	      annualSalary = annual;
	      superRate = superrate;
	      paymentMonth = month;
	      payslip = paysl;
	  }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Payslip = new HashSet<Payslip>();
        }
    
        public int employeeId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Double annualSalary { get; set; }
        public int superRate { get; set; }
        public int paymentMonth { get; set; }

        public Payslip payslip { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payslip> Payslip { get; set; }
    }
}
