//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATO.net.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Diagnostics;

    public partial class Taxthreshold
    {
        public int taxthresholdId { get; set; }
        public Double taxMin { get; set; }
        public Double taxCent { get; set; }
        public Double taxLump { get; set; }
        
        public Boolean HasRows()
        {
            SqlConnection con = new SqlConnection(@"Data Source=(LocalDb)\MSSQLLocalDB;Initial Catalog=ATO.net.Models.Model1;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework");

            Boolean validRowExist = false;
            using (con)
            {
                SqlCommand command = new SqlCommand("SELECT taxthresholdId FROM TaxthresholdSet;", con);
                con.Open();

                SqlDataReader reader = command.ExecuteReader();

                if (reader.HasRows)
                {
                    validRowExist = true;
                }
                else
                {
                    validRowExist = false;
                }
                reader.Close();
            }
            return validRowExist;
        }

        public void InsertToDB(Taxthreshold taxthreshold)
        {
            SqlConnection con = new SqlConnection(@"Data Source=(LocalDb)\MSSQLLocalDB;Initial Catalog=ATO.net.Models.Model1;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework");

            try
            {
                using (con)
                {
                    String query = "INSERT INTO dbo.TaxthresholdSet(taxMin, taxCent, taxLump) VALUES (@taxMin, @taxCent, @taxLump)";
                    con.Open();
                    SqlCommand cmd = new SqlCommand(query, con);
                    cmd.Parameters.AddWithValue("@taxMin", taxthreshold.taxMin);
                    cmd.Parameters.AddWithValue("@taxCent", taxthreshold.taxCent);
                    cmd.Parameters.AddWithValue("@taxLump", taxthreshold.taxLump);
                    cmd.ExecuteNonQuery();
                }
                con.Close();
            }
            catch (Exception ex)
            { throw ex; }
            finally { con.Close(); }
        }

        public List<Taxthreshold> ReadTaxthresholdList()
        {
            SqlConnection con = new SqlConnection(@"Data Source=(LocalDb)\MSSQLLocalDB;Initial Catalog=ATO.net.Models.Model1;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework");
            List<Taxthreshold> taxthresholds = new List<Taxthreshold>();
            try
            {
                using (con)
                {
                    SqlCommand command = new SqlCommand("SELECT * FROM dbo.TaxthresholdSet;", con);
                    con.Open();
                    SqlDataReader reader = command.ExecuteReader();

                    while (reader.Read())
                    {
                        Taxthreshold taxthreshold = new Taxthreshold();
                        taxthreshold.taxMin = Double.Parse((string)reader["taxMin"].ToString());
                        taxthreshold.taxCent = Double.Parse((string)reader["taxCent"].ToString());
                        taxthreshold.taxLump = Double.Parse((string)reader["taxLump"].ToString());
                        taxthresholds.Add(taxthreshold);
                    }
                }
            }
            catch (Exception ex)
            { throw ex; }
            finally { con.Close(); }
            return taxthresholds;
        }


    }

   
}
